### ISSUE TITLE
ERROR: device-make-profile-default

### ISSUE THREAD

**Issue by MantasMikal** [udifuchs/icc-brightness#13]
I'm getting this error after running ./icc-brightness watch on Razer Blade 15 2019 OLED
Kubuntu 19.04
Kernel: 5.3.0-050300-generic
 ```
ERROR: device-make-profile-default
Traceback (most recent call last):
  File "./icc-brightness", line 136, in main
    icc_brightness_apply()
  File "./icc-brightness", line 108, in icc_brightness_apply
    icc_brightness(brightness, max_brightness)
  File "./icc-brightness", line 85, in icc_brightness
    subprocess.check_output(['colormgr', 'import-profile', icc_filepath])
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['colormgr', 'import-profile', '/tmp/brightness_8400_24000.icc']' returned non-zero exit status 1.
^CTraceback (most recent call last):
  File "./icc-brightness", line 157, in <module>
    main()
  File "./icc-brightness", line 145, in main
    time.sleep(1000000)
```
What could be the issue here?

**Comment by ncharles** [comment]
I often have it when the default device is not the screen, but rather something else. Removing the device with colormgr may solve the issue

**Comment by Davidnet** [comment]
@ncharles how to remove the device?

**Comment by udifuchs** [comment]
The latest version of icc-brightness should solve this issue.
If you are still interested in this after all this time, and you still have an issue, please report.
