### ISSUE TITLE
Support for multi LANG enviroment (XPS 15 7950, Ubuntu 19.10)

### ISSUE THREAD

**Issue by jancidlo** [udifuchs/icc-brightness#23]
Hello

I'm using Ubuntu 19.10 with latest updates on Dell XPS 15 7950.
Software icc-brightness is working well on default EN language.
After I changed language to CZ,  software didn't work and I received an error message:

Traceback (most recent call last):
  File "/usr/local/bin/icc-brightness", line 157, in <module>
    main()
  File "/usr/local/bin/icc-brightness", line 132, in main
    icc_brightness_apply()
  File "/usr/local/bin/icc-brightness", line 108, in icc_brightness_apply
    icc_brightness(brightness, max_brightness)
  File "/usr/local/bin/icc-brightness", line 85, in icc_brightness
    subprocess.check_output(['colormgr', 'import-profile', icc_filepath])
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['colormgr', 'import-profile', '/tmp/brightness_78420_120000.icc']' returned non-zero exit status 1.

Here is filtered print of `set` command of working environment:
 LANG=en_US.UTF-8
LANGUAGE=en
LC_ADDRESS=cs_CZ.UTF-8
LC_IDENTIFICATION=cs_CZ.UTF-8
LC_MEASUREMENT=cs_CZ.UTF-8
LC_MONETARY=cs_CZ.UTF-8
LC_NAME=cs_CZ.UTF-8
LC_NUMERIC=cs_CZ.UTF-8
LC_PAPER=cs_CZ.UTF-8
LC_TELEPHONE=cs_CZ.UTF-8
LC_TIME=cs_CZ.UTF-8

and  print of environment that doesn't work:
LANG=cs_CZ.UTF-8
LANGUAGE=cs:en
LC_ADDRESS=cs_CZ.UTF-8
LC_IDENTIFICATION=cs_CZ.UTF-8
LC_MEASUREMENT=cs_CZ.UTF-8
LC_MONETARY=cs_CZ.UTF-8
LC_NAME=cs_CZ.UTF-8
LC_NUMERIC=cs_CZ.UTF-8
LC_PAPER=cs_CZ.UTF-8
LC_TELEPHONE=cs_CZ.UTF-8
LC_TIME=cs_CZ.UTF-8

When I switch language from CZ back to EN, software works well again.

Thank you for your help,
Jindrich

**Comment by udifuchs** [comment]
This issue was fixed in 960c66f71433e7ebc690bd008f207c59b9fd0338
