### ISSUE TITLE
Issues on Arch + Plasma

### ISSUE THREAD

**Issue by mvolf** [udifuchs/icc-brightness#27]
I'm having some weird issues on my Gigabyte Aero 15. I'm using Arch Linux and KDE Plasma.
I've installed the kde-colord and this resulted in script sort of working.
I've added a .desktop file to ~/.config/autostart. When using only this, only the first change of the brightness (using KDE brightness control applet) works. After that first change the controls stop working.
However, when I run 'icc-brightness watch' in console it works as expected on every change.
I noticed some errors in the console when changing the brightness sometimes. Is it possible that these errors crash the script that's run via the .desktop file and this causes it to stop working?

Here are the errors:

`profile path '/org/freedesktop/ColorManager/profiles/icc_d41d8cd98f00b204e9800998ecf8427e_mvolf_1000' not found
ERROR: Error during call to icc_brightness
Traceback (most recent call last):
  File "/usr/bin/icc-brightness", line 114, in handler
    icc_brightness_apply()
  File "/usr/bin/icc-brightness", line 108, in icc_brightness_apply
    icc_brightness(brightness, max_brightness)
  File "/usr/bin/icc-brightness", line 99, in icc_brightness
    subprocess.run(['colormgr', 'delete-profile', object_path], check=True)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['colormgr', 'delete-profile', '/org/freedesktop/ColorManager/profiles/icc_d41d8cd98f00b204e9800998ecf8427e_mvolf_1000']' returned non-zero exit status 1.
ERROR: None
ERROR: Error during call to icc_brightness
Traceback (most recent call last):
  File "/usr/bin/icc-brightness", line 114, in handler
    icc_brightness_apply()
  File "/usr/bin/icc-brightness", line 108, in icc_brightness_apply
    icc_brightness(brightness, max_brightness)
  File "/usr/bin/icc-brightness", line 88, in icc_brightness
    subprocess.run(['colormgr', 'device-add-profile',
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType`

icc-brightness clean doesn't help.

**Comment by udifuchs** [comment]
The error you were seeing should be fixed by commit 6c77394092f5d269f605af82893ac899ae7982f7.
If you still have an issue (after all this time), please reopen.
