### ISSUE TITLE
Does not work on KDE on Aero 15 at all

### ISSUE THREAD

**Issue by xuancong84** [udifuchs/icc-brightness#35]
Both the program and auto-start does not work.
```
xuancong@wxc-aero:~$ icc-brightness watch
ERROR: device-make-profile-default
Traceback (most recent call last):
  File "/usr/local/bin/icc-brightness", line 136, in main
    icc_brightness_apply()
  File "/usr/local/bin/icc-brightness", line 108, in icc_brightness_apply
    icc_brightness(brightness, max_brightness)
  File "/usr/local/bin/icc-brightness", line 85, in icc_brightness
    subprocess.check_output(['colormgr', 'import-profile', icc_filepath])
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['colormgr', 'import-profile', '/tmp/brightness_6000_120000.icc']' returned non-zero exit status 1.
```

**Comment by udifuchs** [comment]
It is weird, there should be another line showing the error message from `colormgr`.
Without more information, I cannot help you.
Considering how old this issue is, I am assuming that it is no longer relevant.
Feel free to re-open if you are still interested in solving this.
