### ISSUE TITLE
Can compile it for Ubuntu 24.-4 but using it results in python errors

### ISSUE THREAD

**Issue by ouboub** [udifuchs/icc-brightness#42]
Hi

I am using Ubuntu 14.04 and python 3.12. I sucessfully compiled icc-brithness, but then

```
/icc-brightness brightness max-brightness
Traceback (most recent call last):
  File "/home/oub/ALLES/src/icc-brightness/./icc-brightness", line 157, in <module>
    main()
  File "/home/oub/ALLES/src/icc-brightness/./icc-brightness", line 148, in main
    brightness = int(sys.argv[1])
                 ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'brightness'
```
is my python version to recent?
thanks and regards

Uwe Brauer

**Comment by agroeschl** [comment]
Hi, i have the same issue. Uwe have you fixed the problem?

**Comment by ouboub** [comment]
> Hi, i have the same issue. Uwe have you fixed the problem?

No unfortunately not, but 
I set the following alias (tcsh shell)
```
brigher:          aliased to sudo brightnessctl set !:1%+
```

**Comment by udifuchs** [comment]
The documentation was confusing. You need to use brightness values instead of the word `brightness`.
For example:
```
icc-brightness 70 100
```
